module TailwindExtra exposing
    ( space_y
    , scroll_mt
    , divide_color
    , max_w_2xl
    , max_w_4xl
    , max_w_5xl
    , max_w_7xl
    , max_w_lg
    , text_white_50
    , text_white_60
    , text_white_70
    , text_white_80
    , text_brand_50
    , text_brand_70
    , text_brand_80
    , bg_transparent
    , bg_current
    , bg_black_50
    , bg_brand_5
    , bg_brand_10
    , bg_brand_20
    , border_black_10
    , border_brand_30
    , border_t_brand
    , border_t_gray_900
    , border_transparent
    , border_white_10
    , group
    , peer
    , not_prose
    , inset_0
    , inset_y_0
    , left_0
    , left_0_5
    , left_half
    , top_0
    , top_0_5
    , top_2
    , right_2
    , ms_8
    , ms_12
    , leading_6
    , leading_7
    , leading_10
    , translate_x_0
    , translate_x_5
    , neg_translate_x_half
    , neg_start_6
    , ring_brand
    , ring_brand_yellow
    , grid_cols_auto_1fr
    , h_35
    , w_35
    )

{-| Typed Tailwind helpers for utilities not yet generated by elm-tailwind-classes.

These fill the gaps left by the auto-generated `Tailwind` module. Each function
uses the `Tailwind` constructor directly (no `Tw.raw`) so the `LlmAgent.NoTailwindRawStrings`
elm-review rule stays green and the elm-tailwind-classes extractor can still
find the class strings statically.

When elm-tailwind-classes adds support for these utilities natively, migrate
callers to the generated versions and delete the corresponding function here.

-}

import Tailwind exposing (Tailwind(..))
import Tailwind.Theme exposing (Color, Spacing, colorToString, spacingToString)


{-| Adds vertical space between child elements.

    TailwindExtra.space_y (Th.s4)  -- "space-y-4"

-}
space_y : Spacing -> Tailwind
space_y spacing =
    Tailwind ("space-y-" ++ spacingToString spacing)


{-| Scroll margin-top — offsets a sticky header when anchor-linking to a section.

    TailwindExtra.scroll_mt (Th.s28)  -- "scroll-mt-28"

-}
scroll_mt : Spacing -> Tailwind
scroll_mt spacing =
    Tailwind ("scroll-mt-" ++ spacingToString spacing)


{-| Colour the divider lines produced by `divide-y` / `divide-x`.

    TailwindExtra.divide_color (Th.gray Th.s100)  -- "divide-gray-100"

-}
divide_color : Color -> Tailwind
divide_color color =
    Tailwind ("divide-" ++ colorToString color)


{-| Caps width at Tailwind's `2xl` container size (42 rem / 672 px). -}
max_w_2xl : Tailwind
max_w_2xl =
    Tailwind "max-w-2xl"


{-| Caps width at Tailwind's `4xl` container size (56 rem / 896 px). -}
max_w_4xl : Tailwind
max_w_4xl =
    Tailwind "max-w-4xl"


{-| Caps width at Tailwind's `5xl` container size (64 rem / 1024 px). -}
max_w_5xl : Tailwind
max_w_5xl =
    Tailwind "max-w-5xl"


{-| Caps width at Tailwind's `7xl` container size (80 rem / 1280 px). -}
max_w_7xl : Tailwind
max_w_7xl =
    Tailwind "max-w-7xl"


{-| Caps width at Tailwind's `lg` container size (32 rem / 512 px). -}
max_w_lg : Tailwind
max_w_lg =
    Tailwind "max-w-lg"


{-| White text at 50 % opacity. -}
text_white_50 : Tailwind
text_white_50 =
    Tailwind "text-white/50"


{-| White text at 60 % opacity. -}
text_white_60 : Tailwind
text_white_60 =
    Tailwind "text-white/60"


{-| White text at 70 % opacity. -}
text_white_70 : Tailwind
text_white_70 =
    Tailwind "text-white/70"


{-| White text at 80 % opacity — used for navbar links on a dark background.

Tailwind opacity-modifier syntax (`text-white/80`) has no generated typed token;
this constant provides a named, searchable alternative.

-}
text_white_80 : Tailwind
text_white_80 =
    Tailwind "text-white/80"


{-| Brand text at 50 % opacity. -}
text_brand_50 : Tailwind
text_brand_50 =
    Tailwind "text-brand/50"


{-| Brand text at 70 % opacity. -}
text_brand_70 : Tailwind
text_brand_70 =
    Tailwind "text-brand/70"


{-| Brand text at 80 % opacity. -}
text_brand_80 : Tailwind
text_brand_80 =
    Tailwind "text-brand/80"


{-| Transparent background — used to reset browser default button backgrounds. -}
bg_transparent : Tailwind
bg_transparent =
    Tailwind "bg-transparent"


{-| `currentColor` background — inherits text colour for SVG fill etc. -}
bg_current : Tailwind
bg_current =
    Tailwind "bg-current"


{-| Black background at 50 % opacity — modal/dialog backdrop. -}
bg_black_50 : Tailwind
bg_black_50 =
    Tailwind "bg-black/50"


{-| Brand background at 5 % opacity. -}
bg_brand_5 : Tailwind
bg_brand_5 =
    Tailwind "bg-brand/5"


{-| Brand background at 10 % opacity. -}
bg_brand_10 : Tailwind
bg_brand_10 =
    Tailwind "bg-brand/10"


{-| Brand background at 20 % opacity. -}
bg_brand_20 : Tailwind
bg_brand_20 =
    Tailwind "bg-brand/20"


{-| Black border at 10 % opacity — subtle outline for colour swatches. -}
border_black_10 : Tailwind
border_black_10 =
    Tailwind "border-black/10"


{-| Brand border at 30 % opacity. -}
border_brand_30 : Tailwind
border_brand_30 =
    Tailwind "border-brand/30"


{-| Top border in the brand colour. -}
border_t_brand : Tailwind
border_t_brand =
    Tailwind "border-t-brand"


{-| Top border in gray-900 — used for dark decorative accents. -}
border_t_gray_900 : Tailwind
border_t_gray_900 =
    Tailwind "border-t-gray-900"


{-| Transparent border — reserves border space without showing colour. -}
border_transparent : Tailwind
border_transparent =
    Tailwind "border-transparent"


{-| White border at 10 % opacity — subtle divider on dark backgrounds. -}
border_white_10 : Tailwind
border_white_10 =
    Tailwind "border-white/10"


{-| Tailwind `group` utility — marks a parent so child `group-*` variants apply. -}
group : Tailwind
group =
    Tailwind "group"


{-| Tailwind `peer` utility — marks a sibling so child `peer-*` variants apply. -}
peer : Tailwind
peer =
    Tailwind "peer"


{-| Opt out of Tailwind Typography prose styles for a subtree. -}
not_prose : Tailwind
not_prose =
    Tailwind "not-prose"


{-| Sets all inset edges to 0 (position: absolute fill). -}
inset_0 : Tailwind
inset_0 =
    Tailwind "inset-0"


{-| Sets vertical inset (top + bottom) to 0. -}
inset_y_0 : Tailwind
inset_y_0 =
    Tailwind "inset-y-0"


{-| Positions element at `left: 0`. -}
left_0 : Tailwind
left_0 =
    Tailwind "left-0"


{-| Positions element at `left: 0.125rem (2px)`. -}
left_0_5 : Tailwind
left_0_5 =
    Tailwind "left-0.5"


{-| Positions element at `left: 50%` — used with `-translate-x-1/2` to centre. -}
left_half : Tailwind
left_half =
    Tailwind "left-1/2"


{-| Positions element at `top: 0`. -}
top_0 : Tailwind
top_0 =
    Tailwind "top-0"


{-| Positions element at `top: 0.125rem (2px)`. -}
top_0_5 : Tailwind
top_0_5 =
    Tailwind "top-0.5"


{-| Positions element at `top: 0.5rem (8px)`. -}
top_2 : Tailwind
top_2 =
    Tailwind "top-2"


{-| Positions element at `right: 0.5rem (8px)`. -}
right_2 : Tailwind
right_2 =
    Tailwind "right-2"


{-| `margin-inline-start: 2rem (32px)` — logical-property equivalent of ml-8. -}
ms_8 : Tailwind
ms_8 =
    Tailwind "ms-8"


{-| `margin-inline-start: 3rem (48px)` — logical-property equivalent of ml-12. -}
ms_12 : Tailwind
ms_12 =
    Tailwind "ms-12"


{-| Line-height 1.5rem (24px). -}
leading_6 : Tailwind
leading_6 =
    Tailwind "leading-6"


{-| Line-height 1.75rem (28px). -}
leading_7 : Tailwind
leading_7 =
    Tailwind "leading-7"


{-| Line-height 2.5rem (40px). -}
leading_10 : Tailwind
leading_10 =
    Tailwind "leading-10"


{-| No horizontal translation (`translateX(0)`). -}
translate_x_0 : Tailwind
translate_x_0 =
    Tailwind "translate-x-0"


{-| Horizontal translation of 1.25rem (20px). -}
translate_x_5 : Tailwind
translate_x_5 =
    Tailwind "translate-x-5"


{-| Horizontal translation of −50% — centres an element when combined with `left-1/2`. -}
neg_translate_x_half : Tailwind
neg_translate_x_half =
    Tailwind "-translate-x-1/2"


{-| `margin-inline-start: -1.5rem` — pulls a list marker into the gutter. -}
neg_start_6 : Tailwind
neg_start_6 =
    Tailwind "-start-6"


{-| Ring in the brand colour. -}
ring_brand : Tailwind
ring_brand =
    Tailwind "ring-brand"


{-| Ring in the brand-yellow colour. -}
ring_brand_yellow : Tailwind
ring_brand_yellow =
    Tailwind "ring-brand-yellow"


{-| Arbitrary grid template: `auto 1fr` — icon + text two-column layout. -}
grid_cols_auto_1fr : Tailwind
grid_cols_auto_1fr =
    Tailwind "grid-cols-[auto_1fr]"


{-| Custom height of 8.75rem (140px) — matches the brand h-35 design token. -}
h_35 : Tailwind
h_35 =
    Tailwind "h-35"


{-| Custom width of 8.75rem (140px) — matches the brand w-35 design token. -}
w_35 : Tailwind
w_35 =
    Tailwind "w-35"
